#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os

from setuptools import find_packages, setup

REQUIRES = [
    'dnspython>=1.11.1',
    'psutil>=1.2.1',
    'python-dateutil>=2.0',
    'python-termstyle>=0.1.10',
    'pytz>=2014.1',
    'redis>=2.10.3',
    'requests>=2.2.0',
]

DATA = [
    ('/opt/intelmq/etc/',
     ['intelmq/bots/BOTS',
      ],
     ),
    ('/opt/intelmq/etc/examples',
     ['intelmq/etc/defaults.conf',
      'intelmq/etc/harmonization.conf',
      'intelmq/etc/pipeline.conf',
      'intelmq/etc/runtime.conf',
      ],
     ),
    ('/opt/intelmq/var/lib/bots/modify/example',
     ['intelmq/bots/experts/modify/examples/default.conf',
      'intelmq/bots/experts/modify/examples/morefeeds.conf',
      ],
     ),
    ('/opt/intelmq/var/log/',
     [],
     ),
    ('/opt/intelmq/var/lib/bots/file-output/',
     [],
     ),
]

exec(open(os.path.join(os.path.dirname(__file__),
                       'intelmq/version.py')).read())  # defines __version__


setup(
    name='intelmq',
    version=__version__,
    maintainer='Sebastian Wagner',
    maintainer_email='wagner@cert.at',
    install_requires=REQUIRES,
    test_suite='intelmq.tests',
    packages=find_packages(),
    package_data={'intelmq': [
        'etc/*.conf',
        'bots/BOTS',
        'bots/experts/modify/*.conf',
    ]
    },
    include_package_data=True,
    url='https://github.com/certtools/intelmq/',
    license='AGPLv3',
    description='IntelMQ is a solution for CERTs to process data feeds, '
                'pastebins, tweets throught a message queue.',
    long_description=open(os.path.join(os.path.dirname(__file__),
                                       'docs/README.rst')).read(),
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'Intended Audience :: Telecommunications Industry',
        'License :: OSI Approved :: GNU Affero General Public License v3',
        'Operating System :: Unix',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Topic :: Security',
    ],
    keywords='incident handling cert csirt',
    data_files=DATA,
    entry_points={
        'console_scripts': [
            'intelmqctl = intelmq.bin.intelmqctl:main',
            'intelmqdump = intelmq.bin.intelmqdump:main',
            'intelmq_psql_initdb = intelmq.bin.intelmq_psql_initdb:main',
            'intelmq.bots.collectors.alienvault_otx.collector = intelmq.bots.collectors.alienvault_otx.collector:AlienVaultOTXCollectorBot.run',
            'intelmq.bots.collectors.bitsight.collector = intelmq.bots.collectors.bitsight.collector:BitsightCollectorBot.run',
            'intelmq.bots.collectors.blueliv.collector_crimeserver = intelmq.bots.collectors.blueliv.collector_crimeserver:BluelivCrimeserverCollectorBot.run',
            'intelmq.bots.collectors.file.collector_file = intelmq.bots.collectors.file.collector_file:FileCollectorBot.run',
            'intelmq.bots.collectors.ftp.collector_ftp = intelmq.bots.collectors.ftp.collector_ftp:FTPCollectorBot.run',
            'intelmq.bots.collectors.ftp.collector_ftps = intelmq.bots.collectors.ftp.collector_ftps:FTPSCollectorBot.run',
            'intelmq.bots.collectors.http.collector_http = intelmq.bots.collectors.http.collector_http:HTTPCollectorBot.run',
            'intelmq.bots.collectors.http.collector_http_stream = intelmq.bots.collectors.http.collector_http_stream:HTTPStreamCollectorBot.run',
            'intelmq.bots.collectors.mail.collector_mail_attach = intelmq.bots.collectors.mail.collector_mail_attach:MailAttachCollectorBot.run',
            'intelmq.bots.collectors.mail.collector_mail_url = intelmq.bots.collectors.mail.collector_mail_url:MailURLCollectorBot.run',
            'intelmq.bots.collectors.misp.collector = intelmq.bots.collectors.misp.collector:MISPCollectorBot.run',
            'intelmq.bots.collectors.n6.collector_stomp = intelmq.bots.collectors.n6.collector_stomp:n6stompCollectorBot.run',
            'intelmq.bots.collectors.rt.collector_rt = intelmq.bots.collectors.rt.collector_rt:RTCollectorBot.run',
            'intelmq.bots.collectors.xmpp.collector = intelmq.bots.collectors.xmpp.collector:XMPPCollectorBot.run',
            'intelmq.bots.experts.abusix.expert = intelmq.bots.experts.abusix.expert:AbusixExpertBot.run',
            'intelmq.bots.experts.asn_lookup.expert = intelmq.bots.experts.asn_lookup.expert:ASNLookupExpertBot.run',
            'intelmq.bots.experts.certat_contact.expert = intelmq.bots.experts.certat_contact.expert:CERTatContactExpertBot.run',
            'intelmq.bots.experts.cymru_whois.expert = intelmq.bots.experts.cymru_whois.expert:CymruExpertBot.run',
            'intelmq.bots.experts.deduplicator.expert = intelmq.bots.experts.deduplicator.expert:DeduplicatorExpertBot.run',
            'intelmq.bots.experts.filter.expert = intelmq.bots.experts.filter.expert:FilterExpertBot.run',
            'intelmq.bots.experts.generic_db_lookup.expert = intelmq.bots.experts.generic_db_lookup.expert:GenericDBLookupExpertBot.run',
            'intelmq.bots.experts.gethostbyname.expert = intelmq.bots.experts.gethostbyname.expert:GethostbynameExpertBot.run',
            'intelmq.bots.experts.maxmind_geoip.expert = intelmq.bots.experts.maxmind_geoip.expert:GeoIPExpertBot.run',
            'intelmq.bots.experts.modify.expert = intelmq.bots.experts.modify.expert:ModifyExpertBot.run',
            'intelmq.bots.experts.reverse_dns.expert = intelmq.bots.experts.reverse_dns.expert:ReverseDnsExpertBot.run',
            'intelmq.bots.experts.rfc1918.expert = intelmq.bots.experts.rfc1918.expert:RFC1918ExpertBot.run',
            'intelmq.bots.experts.ripencc_abuse_contact.expert = intelmq.bots.experts.ripencc_abuse_contact.expert:RIPENCCExpertBot.run',
            'intelmq.bots.experts.taxonomy.expert = intelmq.bots.experts.taxonomy.expert:TaxonomyExpertBot.run',
            'intelmq.bots.experts.tor_nodes.expert = intelmq.bots.experts.tor_nodes.expert:TorExpertBot.run',
            'intelmq.bots.experts.url2fqdn.expert = intelmq.bots.experts.url2fqdn.expert:Url2fqdnExpertBot.run',
            'intelmq.bots.outputs.amqptopic.output = intelmq.bots.outputs.amqptopic.output:AMQPTopicBot.run',
            'intelmq.bots.outputs.file.output = intelmq.bots.outputs.file.output:FileBot.run',
            'intelmq.bots.outputs.mongodb.output = intelmq.bots.outputs.mongodb.output:MongoDBOutputBot.run',
            'intelmq.bots.outputs.postgresql.output = intelmq.bots.outputs.postgresql.output:PostgreSQLBot.run',
            'intelmq.bots.outputs.redis.output = intelmq.bots.outputs.redis.output:RedisOutputBot.run',
            'intelmq.bots.outputs.restapi.output = intelmq.bots.outputs.restapi.output:RestAPIOutputBot.run',
            'intelmq.bots.outputs.stomp.output = intelmq.bots.outputs.stomp.output:StompOutputBot.run',
            'intelmq.bots.outputs.tcp.output = intelmq.bots.outputs.tcp.output:TCPOutputBot.run',
            'intelmq.bots.outputs.udp.output = intelmq.bots.outputs.udp.output:UDPBot.run',
            'intelmq.bots.outputs.xmpp.output = intelmq.bots.outputs.xmpp.output:XMPPOutputBot.run',
            'intelmq.bots.parsers.abusech.parser_domain = intelmq.bots.parsers.abusech.parser_domain:AbusechDomainParserBot.run',
            'intelmq.bots.parsers.abusech.parser_ip = intelmq.bots.parsers.abusech.parser_ip:AbusechIPParserBot.run',
            'intelmq.bots.parsers.alienvault.parser = intelmq.bots.parsers.alienvault.parser:AlienVaultParserBot.run',
            'intelmq.bots.parsers.alienvault.parser_otx = intelmq.bots.parsers.alienvault.parser_otx:AlienVaultOTXParserBot.run',
            'intelmq.bots.parsers.autoshun.parser = intelmq.bots.parsers.autoshun.parser:AutoshunParserBot.run',
            'intelmq.bots.parsers.bitsight.parser = intelmq.bots.parsers.bitsight.parser:BitsightParserBot.run',
            'intelmq.bots.parsers.blocklistde.parser = intelmq.bots.parsers.blocklistde.parser:BlockListDEParserBot.run',
            'intelmq.bots.parsers.blueliv.parser_crimeserver = intelmq.bots.parsers.blueliv.parser_crimeserver:BluelivCrimeserverParserBot.run',
            'intelmq.bots.parsers.ci_army.parser = intelmq.bots.parsers.ci_army.parser:CIArmyParserBot.run',
            'intelmq.bots.parsers.cleanmx.parser_phishing = intelmq.bots.parsers.cleanmx.parser_phishing:CleanMXPhishingParserBot.run',
            'intelmq.bots.parsers.cleanmx.parser_virus = intelmq.bots.parsers.cleanmx.parser_virus:CleanMXVirusParserBot.run',
            'intelmq.bots.parsers.cymru_full_bogons.parser = intelmq.bots.parsers.cymru_full_bogons.parser:CymruFullBogonsParserBot.run',
            'intelmq.bots.parsers.danger_rulez.parser = intelmq.bots.parsers.danger_rulez.parser:BruteForceBlockerParserBot.run',
            'intelmq.bots.parsers.dragonresearchgroup.parser_ssh = intelmq.bots.parsers.dragonresearchgroup.parser_ssh:DragonResearchGroupSSHParserBot.run',
            'intelmq.bots.parsers.dragonresearchgroup.parser_vnc = intelmq.bots.parsers.dragonresearchgroup.parser_vnc:DragonResearchGroupVNCParserBot.run',
            'intelmq.bots.parsers.dshield.parser_asn = intelmq.bots.parsers.dshield.parser_asn:DShieldASNParserBot.run',
            'intelmq.bots.parsers.dshield.parser_block = intelmq.bots.parsers.dshield.parser_block:DshieldBlockParserBot.run',
            'intelmq.bots.parsers.dshield.parser_domain = intelmq.bots.parsers.dshield.parser_domain:DshieldDomainParserBot.run',
            'intelmq.bots.parsers.dyn.parser = intelmq.bots.parsers.dyn.parser:DynParserBot.run',
            'intelmq.bots.parsers.fraunhofer.parser_dga = intelmq.bots.parsers.fraunhofer.parser_dga:FraunhoferDGAParserBot.run',
            'intelmq.bots.parsers.generic.parser_csv = intelmq.bots.parsers.generic.parser_csv:GenericCsvParserBot.run',
            'intelmq.bots.parsers.hphosts.parser = intelmq.bots.parsers.hphosts.parser:HpHostsParserBot.run',
            'intelmq.bots.parsers.json.parser = intelmq.bots.parsers.json.parser:JSONParserBot.run',
            'intelmq.bots.parsers.malc0de.parser_domain_blacklist = intelmq.bots.parsers.malc0de.parser_domain_blacklist:Malc0deDomainBlacklistParserBot.run',
            'intelmq.bots.parsers.malc0de.parser_ip_blacklist = intelmq.bots.parsers.malc0de.parser_ip_blacklist:Malc0deIPBlacklistParserBot.run',
            'intelmq.bots.parsers.malwaredomainlist.parser = intelmq.bots.parsers.malwaredomainlist.parser:MalwareDomainListParserBot.run',
            'intelmq.bots.parsers.malwaredomains.parser = intelmq.bots.parsers.malwaredomains.parser:MalwareDomainsParserBot.run',
            'intelmq.bots.parsers.malwarepatrol.parser_dansguardian = intelmq.bots.parsers.malwarepatrol.parser_dansguardian:DansParserBot.run',
            'intelmq.bots.parsers.misp.parser = intelmq.bots.parsers.misp.parser:MISPParserBot.run',
            'intelmq.bots.parsers.n6.parser_n6stomp = intelmq.bots.parsers.n6.parser_n6stomp:N6StompParserBot.run',
            'intelmq.bots.parsers.openbl.parser = intelmq.bots.parsers.openbl.parser:OpenBLParserBot.run',
            'intelmq.bots.parsers.openphish.parser = intelmq.bots.parsers.openphish.parser:OpenPhishParserBot.run',
            'intelmq.bots.parsers.phishtank.parser = intelmq.bots.parsers.phishtank.parser:PhishTankParserBot.run',
            'intelmq.bots.parsers.shadowserver.parser = intelmq.bots.parsers.shadowserver.parser:ShadowserverParserBot.run',
            'intelmq.bots.parsers.spamhaus.parser_cert = intelmq.bots.parsers.spamhaus.parser_cert:SpamhausCERTParserBot.run',
            'intelmq.bots.parsers.spamhaus.parser_drop = intelmq.bots.parsers.spamhaus.parser_drop:SpamhausDropParserBot.run',
            'intelmq.bots.parsers.taichung.parser = intelmq.bots.parsers.taichung.parser:TaichungCityNetflowParserBot.run',
            'intelmq.bots.parsers.turris.parser = intelmq.bots.parsers.turris.parser:TurrisGreylistParserBot.run',
            'intelmq.bots.parsers.urlvir.parser_hosts = intelmq.bots.parsers.urlvir.parser_hosts:URLVirHostsParserBot.run',
            'intelmq.bots.parsers.urlvir.parser_ips = intelmq.bots.parsers.urlvir.parser_ips:URLVirIPsParserBot.run',
            'intelmq.bots.parsers.vxvault.parser = intelmq.bots.parsers.vxvault.parser:VXVaultParserBot.run',
        ],
    },
    scripts=[
        'intelmq/bots/experts/tor_nodes/update-tor-nodes',
        'intelmq/bots/experts/maxmind_geoip/update-geoip-data',
        'intelmq/bots/experts/asn_lookup/update-asn-data',
    ],
)
