#!/bin/bash

echo 'This script is deprecated and will be removed in version 3.0.
Please use the command "intelmq.bots.experts.tor_nodes.expert --update-database" instead.'

intelmq.bots.experts.tor_nodes.expert --update-database
