#!/bin/bash
# Update tor nodes data
# The target file must be given as only argument on the commandline.
PATH=/bin:/usr/bin

# set the http proxy here:
# export http_proxy=http://proxy.example.com:8080/
# export HTTPS_PROXY=https://proxy.example.com:8080/
# export FTP_PROXY=ftp://proxy.example.com:8080/


set -e
trap cleanup EXIT

fail()
{
  echo >&2 "$@"
  exit 23
}

setup()
{
  [ "$#" -eq 1 ] || fail "Exactly one argument DESTINATION-FILE must be given."
  DEST_FILE="$1"
  TMP_DIR=`mktemp -d`
  dest_dir=`dirname "$DEST_FILE"`
  [ -d "$dest_dir" ] || mkdir -p "$dest_dir"
}

cleanup()
{
  [ -d "$dest_dir" ] && rm -rf "$TMP_DIR"
}

fetch_and_install()
{
  cd "$TMP_DIR"
  #-k parameter added for ignoring wrong certificate on the server
  # 17.12.2018: IntelMQ now uses another source (but it seems to me there is less IPs found):
  # curl -s -S https://check.torproject.org/exit-addresses | awk '/ExitAddress/ {print $2}' > tor_nodes.dat
  # see https://github.com/certtools/intelmq/issues/1289
  curl -sk -O https://internet2.us/static/latest.bz2
  bunzip2 -q -c latest.bz2 >tor_nodes.dat
  mv -f tor_nodes.dat "$DEST_FILE"
}

setup "$@"
fetch_and_install
