#!/bin/bash

echo 'This script is deprecated and will be removed in version 3.0.
Please use the command "intelmq.bots.experts.asn_lookup.expert --update-database" instead.' > /dev/stderr

intelmq.bots.experts.asn_lookup.expert --update-database
