---
- name: Update apt cache if not done today
  apt: update_cache=yes cache_valid_time=86400

- name: Install system package requirments with apt
  apt: pkg={{ item }} state=latest
  with_items: common.system_packages
  sudo: yes

- name: Install python package requirements with pip
  pip: name={{ item }}
  with_items: common.python_packages
  sudo: yes
